### PR TITLE
Fixed manufacturer device id shown in grid

### PR DESCRIPTION
**Pull request by BlueAndi**

### CODE REVIEW

**Comment by BlueAndi** [comment]
My last bugfix for today. ;-)
Good night!

**Comment by grodansparadis** [comment]
Andreas Merkle skrev den 2015-01-29 23:04:
>
> My last bugfix for today. ;-)
> Good night!
>

Sweet dreams.  We have a blizzard here tonight. Perfect for programming. 
Take care of the snow tomorrow.

-- 
Be Hungry - Stay Foolish!
Åke Hedman, Grodans Paradis AB / Paradise of the Frog
Brattbergavägen 17, 82050 LOS, SWEDEN
Phone: +46 (0)840011835 CellPhone: +46 (0)730-533146
http://www.grodansparadis.com http://www.vscp.org


---
Detta e-postmeddelande har sökts igenom efter virus med antivirusprogram från Avast.
http://www.avast.com

**Comment by grodansparadis** [comment]
Thanks

**Comment by BlueAndi** [comment]
As you said, it snowed today and as I drove back from the company, a hour ago, it was very slippery on the road.

**Pull request merged**
