### PR TITLE
Dangerous use of xxx::doCmdDataAvailable()

### PR DESCRIPTION
**Pull request by BlueAndi**

### CODE REVIEW

**Comment by grodansparadis** [comment]
hmmmm....

I don't like the inflating use of VSCP_ERROR_ERROR- Better to make all 
errors negative. Question is if that have any side effects? Need to 
check before going that path. But definitely the way to go.

Andreas Merkle skrev den 2015-05-03 20:57:
>
> BlueAndi wants to merge 3 commits into grodansparadis:master from 
> BlueAndi:master:
>
> ------------------------------------------------------------------------
>
>
>         You can view, comment on, or merge this pull request online at:
>
> https://github.com/grodansparadis/vscp_software/pull/130
>
>
>         Commit Summary
>
>   * Merge pull request #1 from grodansparadis/master
>   * The method xxx::doCmdDataAvailable() returned with positive error
>     numbers, but it is described to return only negative return
>     values. This is fixed by using only VSCP_ERROR_ERROR (-1) in
>     VscpRemoteTcpIf::doCmdDataAvailable and using 0 in
>     CDllWrapper::doCmdDataAvailable.
>   * Merge branch 'master' of https://github.com/BlueAndi/vscp_software
>
>
>         File Changes
>
>   * *M* src/vscp/common/canalsuperwrapper.cpp
>     <https://github.com/grodansparadis/vscp_software/pull/130/files#diff-0>
>     (14)
>   * *M* src/vscp/common/dllwrapper.cpp
>     <https://github.com/grodansparadis/vscp_software/pull/130/files#diff-1>
>     (10)
>   * *M* src/vscp/common/vscpremotetcpif.cpp
>     <https://github.com/grodansparadis/vscp_software/pull/130/files#diff-2>
>     (12)
>
>
>         Patch Links:
>
>   * https://github.com/grodansparadis/vscp_software/pull/130.patch
>   * https://github.com/grodansparadis/vscp_software/pull/130.diff
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/grodansparadis/vscp_software/pull/130>.
>

-- 
Be Hungry - Stay Foolish!
Åke Hedman, Grodans Paradis AB / Paradise of the Frog
Brattbergavägen 17, 82050 LOS, SWEDEN
Phone: +46 (0)840011835 CellPhone: +46 (0)730-533146
http://www.grodansparadis.com http://www.vscp.org



---
Detta e-postmeddelande har sökts igenom efter virus med antivirusprogram från Avast.
http://www.avast.com

**Comment by BlueAndi** [comment]
Using VSCP_ERROR_ERROR was the only possibility in my eyes without changing too much.
I was afraid to change all error codes (VSCP_ERROR_... and CANAL_ERROR_...) in negative values, as you mention because of side effects.
How shall we proceed?

**Comment by BlueAndi** [comment]
*argh* ... how can I remove the last commit from this pull request?

**Comment by grodansparadis** [comment]
I just checked fast and it should be no problem as far as I can see. But need to check it more before I dare to do it. Merge this and will try to remember to change this one. Probably will forget it...

**Comment by grodansparadis** [comment]
https://help.github.com/articles/reverting-a-pull-request/

Andreas Merkle skrev den 2015-05-05 20:47:
>
> /argh/ ... how can I remove the last commit from this pull request?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/grodansparadis/vscp_software/pull/130#issuecomment-99177999>.
>

-- 
Be Hungry - Stay Foolish!
Åke Hedman, Grodans Paradis AB / Paradise of the Frog
Brattbergavägen 17, 82050 LOS, SWEDEN
Phone: +46 (0)840011835 CellPhone: +46 (0)730-533146
http://www.grodansparadis.com http://www.vscp.org



---
Detta e-postmeddelande har sökts igenom efter virus med antivirusprogram från Avast.
http://www.avast.com

**Comment by BlueAndi** [comment]
You merged now my last commit too ... but this was not ready and tested and a ';' is missing there :-(

**Comment by grodansparadis** [comment]
Ousch...  Do you fix that?

Andreas Merkle skrev den 2015-05-05 21:37:
>
> You merged now my last commit too ... but this was not ready and 
> tested and a ';' is missing there :-(
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/grodansparadis/vscp_software/pull/130#issuecomment-99198599>.
>

-- 
Be Hungry - Stay Foolish!
Åke Hedman, Grodans Paradis AB / Paradise of the Frog
Brattbergavägen 17, 82050 LOS, SWEDEN
Phone: +46 (0)840011835 CellPhone: +46 (0)730-533146
http://www.grodansparadis.com http://www.vscp.org



---
Detta e-postmeddelande har sökts igenom efter virus med antivirusprogram från Avast.
http://www.avast.com

**Comment by BlueAndi** [comment]
The current pull request contains the ';' ... so it is compileable. First tests looks good.

**Pull request merged**
