### PR TITLE
Block download is running now.

### PR DESCRIPTION
**Pull request by BlueAndi**
But block CRC fails ... anyway we are getting closer to a full software update (hopefully).

### CODE REVIEW

**Comment by grodansparadis** [comment]
I will merge after the release. Thanks!

**Comment by grodansparadis** [comment]
Merge after all. Does not compile clean anymore so I have to check code anyway.

**Comment by BlueAndi** [comment]
Hmm ... compiles at my side with my changes.

**Comment by grodansparadis** [comment]
Last patch. Fixed with this. Thanks!

**Pull request merged**
